# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cropdata',
            fields=[
                ('state', models.CharField(db_column='State', max_length=10)),
                ('district', models.CharField(db_column='District', max_length=15)),
                ('year', models.CharField(db_column='Year', max_length=4)),
                ('season', models.CharField(db_column='Season', max_length=11)),
                ('crop', models.CharField(db_column='Crop', max_length=25)),
                ('production', models.CharField(db_column='Production', max_length=10)),
                ('productivity', models.CharField(blank=True, db_column='Productivity', max_length=12, null=True)),
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cropdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'info',
                'managed': False,
            },
        ),
    ]
