# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cropdata',
            fields=[
                ('state', models.CharField(db_column='State', max_length=20)),
                ('district', models.CharField(db_column='District', max_length=30)),
                ('year', models.IntegerField(db_column='Year')),
                ('season', models.CharField(db_column='Season', max_length=11)),
                ('crop', models.CharField(db_column='Crop', max_length=25)),
                ('production', models.IntegerField(db_column='Production')),
                ('productivity', models.DecimalField(blank=True, db_column='Productivity', decimal_places=2, max_digits=20, null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cropdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('district', models.CharField(db_column='District', max_length=25)),
                ('year', models.IntegerField(db_column='Year')),
                ('january', models.IntegerField(db_column='January')),
                ('february', models.IntegerField(db_column='February')),
                ('march', models.IntegerField(db_column='March')),
                ('april', models.IntegerField(db_column='April')),
                ('may', models.IntegerField(db_column='May')),
                ('june', models.IntegerField(db_column='June')),
                ('july', models.IntegerField(db_column='July')),
                ('august', models.IntegerField(db_column='August')),
                ('september', models.IntegerField(db_column='September')),
                ('october', models.IntegerField(db_column='October')),
                ('november', models.IntegerField(db_column='November')),
                ('december', models.IntegerField(db_column='December')),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pressure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('district', models.CharField(db_column='District', max_length=25)),
                ('year', models.IntegerField(db_column='Year')),
                ('january', models.IntegerField(db_column='January')),
                ('february', models.IntegerField(db_column='February')),
                ('march', models.IntegerField(db_column='March')),
                ('april', models.IntegerField(db_column='April')),
                ('may', models.IntegerField(db_column='May')),
                ('june', models.IntegerField(db_column='June')),
                ('july', models.IntegerField(db_column='July')),
                ('august', models.IntegerField(db_column='August')),
                ('september', models.IntegerField(db_column='September')),
                ('october', models.IntegerField(db_column='October')),
                ('november', models.IntegerField(db_column='November')),
                ('december', models.IntegerField(db_column='December')),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
