# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdata', '0004_auto_20180123_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='entry_time',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
