# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdata', '0006_auto_20180124_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
